'use strict';var my={TAB:0,Vi:1,sm:2},ny=function(a){Ob("MediaRouter.CastStreaming.Start.Success",a,my)};var oy=qb("mr.mirror.cast.LogUploader"),qy=function(a,b,c){py("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},py=function(a,b,c,d){if(0==b.size)oy.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Tv("https://clients2.google.com/cr/report",function(a){a=a.target;
var b=null;cw(a)?(b=dw(a),oy.info("Upload to Crash succeeded: "+b)):oy.info("Upload to Crash failed. HTTP status: "+a.Va());d&&d(b)},"POST",e,void 0,3E4)}};var ry=function(){this.b=0;lj(this)},ty=function(){sy||(sy=new ry);return sy},uy=function(){var a=ty(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&c&&d-a.b<c?!1:Math.random()<b.fraction};ry.prototype.ua=function(){return"mirror.cast.LogUtils"};ry.prototype.Ta=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};ry.prototype.Wa=function(){var a=jj(this);this.b=a&&a.lastAutoSubmitMillis||0};var sy=null;qb("mr.mirror.cast.LogUtils");var vy={Fu:"OFFER",Zq:"ANSWER",cv:"PRESENTATION",Ms:"GET_STATUS",Wv:"STATUS_RESPONSE",Ls:"GET_CAPABILITIES",xr:"CAPABILITIES_RESPONSE",Dv:"RPC"};var wy=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},zy=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;xy(JSON.parse(a),function(a){b=yy(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},yy=function(a){var b=new wy;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Ay(a.seqNum,function(a){b.f=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=la(Object.keys(vy)),e=d.next();!e.done;e=d.next())if(vy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(xa(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}xy(a.error,function(a){b.error=By(a)},function(){throw Error('"error" must be an Object');});xy(a.answer,function(a){b.b=Cy(a)},function(){throw Error('"answer" must be an Object');});xy(a.status,function(a){b.status=Dy(a)},function(){throw Error('"status" must be an Object');
});xy(a.capabilities,function(a){b.capabilities=Ey(a)},function(){throw Error('"capabilities" must be an Object');});return b},xy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Ay=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Fy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Gy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Hy=function(){this.j=null;this.b=[];this.f=
[];this.h=this.g=this.s=null},Cy=function(a){var b=new Hy;Ay(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});Fy(a.sendIndexes,function(a){b.b=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Fy(a.ssrcs,function(a){b.f=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.s=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.h=String(a.castMode));
return b},Iy=function(){this.details=this.description=this.code=null},By=function(a){var b=new Iy;Ay(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));xy(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Jy=function(){this.f=this.b=null},Dy=function(a){var b=new Jy;Ay(a.wifiSnr,function(a){b.b=a},function(){throw Error('"status.wifiSnr" must be a number');
});Fy(a.wifiSpeed,function(a){b.f=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Ky=function(){this.f=this.b=null},Ey=function(a){var b=new Ky;Gy(a.mediaCaps,function(a){b.b=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.f=a.map(function(a){var b;xy(a,function(a){b=Ly(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},My=function(){this.h=this.m=this.s=this.j=this.u=this.b=this.o=this.f=this.initDataTypes=this.g=null},Ly=function(a){var b=new My;"keySystemName"in a&&(b.g=String(a.keySystemName));Gy(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Gy(a.codecs,function(a){b.f=a},function(){throw Error('"capabilities.codecs" must be an array');});Gy(a.secureCodecs,function(a){b.o=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Gy(a.audioRobustness,function(a){b.b=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Gy(a.videoRobustness,function(a){b.u=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.s=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var Ny=function(a){this.l=qb("mr.mirror.cast.MessageDispatcher");this.g=a;this.b=null;this.f=new Map;this.h=0},Oy=function(a,b,c){if(a.f.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.f.set(b,c);a.h=0;xb(a.l,"Added subscriber for "+b+"-type messages.");a.b||(a.b=lx(a.g),a.b.onMessage=a.j.bind(a))},Py=function(a,b){a.f.delete(b)&&xb(a.l,function(){return"Removed subscriber of "+b+"-type messages."});0==a.f.size&&a.b&&(a.b.Ra(),a.b=null)};
Ny.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Qy=function(a,b,c,d,e){var f=null,h=function(){Py(a,c);null!=f&&(clearTimeout(f),f=null)};try{Oy(a,c,function(a){e(a)&&h()})}catch(k){e(null,k);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Ny.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=zy(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.f.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.h?v(this.l,b):xb(this.l,b);++this.h}};var Ry=function(){this.b=Promise.resolve(1)},Ty=function(a,b,c){return Sy(a,function(a){return a==b},c)},Uy=function(a,b){var c=[3,4];return Sy(a,function(a){return-1!=c.indexOf(a)},b)},Vy=function(a,b){a.b=a.b.catch(function(){return 1});return Sy(a,function(){return!0},b)},Sy=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.b=a.b.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Wy(a);try{var h=c(f)}catch(t){h=
Promise.reject(t)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.b)throw Error("A prior operation that started at "+(a+" did not complete."));return f.b})},function(a){e(a);throw a;});return f},Wy=function(a){this.f=a;this.b=null},Xy=function(a,b){a.b="number"===typeof b?b:a.f};var Yy=chrome.cast.streaming,$y=function(a,b,c,d,e){this.F=a.sessionId;this.u=a.bg;this.K=a.le;this.h=b;this.L=c;this.C=d;this.la=Zy(e,"onAnswer",this.u);this.M=Zy(e,"onSessionStop",this.u);this.l=qb("mr.mirror.cast.StreamingLaunchWorkflow");this.A=new Ry;this.m=this.B=this.o=this.f=this.b=this.s=this.j=this.g=null};
$y.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof az,f=b instanceof az;(e&&b&&!f||f&&a&&!e)&&Ub("Mixing remoting and non-remoting tracks");return Ty(this.A,1,function(e){d.g=a;d.j=b;d.s=c;d.l.info(function(){return"Launching streaming for "+bz(d)+" "+("to a "+d.K+".")});return cz(d).then(d.D.bind(d)).then(function(a){return dz(d,a).then(function(b){d.la();var c=ez(d,b,a);d.b=fz(d,d.b,c);d.f=fz(d,d.f,c);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.B=!!b.g;d.m=function(a,b){a==d.b?d.s.de("Audio stream (id="+a+") error: "+b):a==d.f&&d.s.de("Video stream (id="+a+") error: "+b)};Yy.rtpStream.onError.addListener(d.m);return gz(d,b,c)})}).then(function(){d.l.info(function(){return"Launched streaming for "+bz(d)});d.s.yf(d);Xy(e,2);return{Jn:d.b,zq:d.f}})})};
$y.prototype.stop=function(){var a=this;return Vy(this.A,function(b){if(!a.g&&!a.j)return Xy(b,1),Promise.resolve();a.l.info(function(){return"Stopping streaming for "+bz(a)+"."});a.m&&(Yy.rtpStream.onError.removeListener(a.m),a.m=null);if(a.s){var c=a.s.gg();a.s=null}else c=Promise.resolve();return c.then(function(){a.b&&(Yy.rtpStream.stop(a.b),Yy.rtpStream.destroy(a.b),a.b=null);a.f&&(Yy.rtpStream.stop(a.f),Yy.rtpStream.destroy(a.f),a.f=null);a.o&&(Yy.udpTransport.destroy(a.o),a.o=null);a.M();a.l.info(function(){return"Stopped streaming for "+
bz(a)+"."});a.g=null;a.j=null;Xy(b,1)})})};
var hz=function(a,b){var c=JSON.stringify(b);return Promise.all([a.b&&new Promise(function(b){return Yy.rtpStream.getRawEvents(a.b,c,b)}),a.f&&new Promise(function(b){return Yy.rtpStream.getRawEvents(a.f,c,b)})]).catch(function(b){a.l.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},iz=function(a){return Promise.all([a.b&&new Promise(function(b){return Yy.rtpStream.getStats(a.b,b)}),a.f&&
new Promise(function(b){return Yy.rtpStream.getStats(a.f,b)})]).catch(function(b){a.l.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[{}].concat(xa(a.filter(function(a){return!!a}))))})},bz=function(a){if(a.g&&a.j)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.g instanceof az||a.j instanceof az?b+"remoting":b+"streaming"},cz=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(Yy.rtpStream.destroy(c),c=null);e&&!a.j&&(Yy.rtpStream.destroy(e),e=null);a.l.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.b=c;a.f=e;a.o=f;b()};a.g instanceof az||a.j instanceof az?Yy.session.create(null,null,c):Yy.session.create(a.g,a.j,c)})};
$y.prototype.D=function(){for(var a=kh(),b=kh(),c=[],d=la([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,h=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,t=la(Yy.rtpStream.getSupportedParams(e)),y=t.next();!y.done;y=t.next())y=y.value,y.payload.payloadType=h,y.payload.maxLatency=this.h.maxLatencyMillis,y.payload.minLatency=this.h.minLatencyMillis,y.payload.animatedLatency=this.h.animatedLatencyMillis,y.payload.ssrc=
k,y.payload.clockRate=m,y.payload.aesKey=a,y.payload.aesIvMask=b,f?(y.payload.channels=2,y.payload.maxBitrate=this.h.audioBitrate,y.payload.maxFrameRate=100):(y.payload.minBitrate=this.h.minVideoBitrate,y.payload.maxBitrate=this.h.maxVideoBitrate,y.payload.maxFrameRate=this.h.maxFrameRate),c.push(new jz(e,y));return c};
var fz=function(a,b,c){b&&!c.some(function(a){return a.df==b})&&(v(a.l,"Destroying RTP stream not selected by the receiver: id="+b),Yy.rtpStream.destroy(b),b=null);return b},dz=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,k={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.h.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.h.dscpEnabled&&(k.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.h.maxWidth,height:a.h.maxHeight}]});e.push(k)}var m=a.g instanceof az||a.j instanceof az?"remoting":"mirroring",t={type:"OFFER",sessionId:a.F,seqNum:tl(a.L),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.l.info(function(){return"Sending OFFER message: "+JSON.stringify(t)});Qy(a.C,t,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.b){if(b.f!=t.seqNum)return v(a.l,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.b.h)&&e!=m||!e&&"mirroring"!=m)&&a.l.error("Expected receiver to ANSWER with castMode="+m+", but got: "+e);xb(a.l,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},ez=function(a,b,c){if(b.b.length!=b.f.length)return a.l.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.b.length;e={candidate:e.candidate},++f){var h=b.b[f];if(0>h||h>=
c.length)return a.l.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.df==a.candidate.df}}(e)))return a.l.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.f[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.l.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},gz=function(a,b,c){var d=null,e=function(){d&&(Yy.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.j||2344;a.l.info(function(){return"Starting RTP streams to receiver at "+(a.u+":"+f)+(" for selected offers: "+JSON.stringify(c))});var m=a.o||-1;a.h.dscpEnabled&&(a.l.info("Enabled DSCP in sender."),Yy.udpTransport.setOptions(m,{DSCP:!0}));Yy.udpTransport.setDestination(m,{address:a.u,port:f});var t=new Set(c.map(function(a){return a.df}));
d=function(a){t.delete(a);0==t.size&&e()};Yy.rtpStream.onStarted.addListener(d);m=la(c);for(var y=m.next();!y.done;y=m.next())y=y.value,Yy.rtpStream.toggleLogging(y.df,a.h.enableLogging),Yy.rtpStream.start(y.df,y.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},Zy=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.l.error("Error from testHooks."+b,e)}}:function(){}},jz=function(a,b){this.df=
a;this.params=b},az=function(){};var mz=function(a,b,c,d,e,f){this.m=a;this.C=kz(b,this.m.xb);this.L=new $y(this.m.xb,c,d,e,f);this.B=e;this.j=new Ry;this.h=new lz;this.A=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.l=qb("mr.mirror.cast.MediaRemoter");this.u=this.b=this.s=this.g=this.D=null;this.f=!0;this.o=this.F.bind(this)};
mz.prototype.fb=function(a,b){var c=this;return Ty(this.j,1,function(d){c.D=a;c.g=b;var e=c.A.createInterfacePtrAndBind();c.A.setConnectionErrorHandler(function(){c.l.info("Remoter mojo pipe connection error.");nz(c)});c.b=new mojo.MirrorServiceRemotingSourcePtr;var f=Cg(c.m.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.m.mediaSource);c.l.info("Connecting remoter to browser: tabId="+f);(jg.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.b));
c.b.ptr.setConnectionErrorHandler(function(){c.l.info("RemotingSource mojo pipe connection error.");nz(c)});return oz(c).then(function(){if(c.f)c.b.onSinkAvailable(c.C);Xy(d,2)})})};
var nz=function(a){return Vy(a.j,function(b){a.b&&(a.b.ptr.reset(),a.b=null);var c=a.s;a.s=null;a.g=null;a.D=null;a.A.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.o);return new Promise(function(d){window.setTimeout(function(){pz(a).then(function(){Xy(b,1);d();c&&c()})},250)})})};mz.prototype.Zp=function(a){qz(this.h,a)};mz.prototype.sendMessageToSink=mz.prototype.Zp;mz.prototype.yf=function(a){this.g&&this.g.yf(a)};
mz.prototype.gg=function(){return this.g?this.g.gg():Promise.resolve()};mz.prototype.de=function(a,b){this.l.error("Error during streaming: "+a,b);if(this.b)this.b.onError();nz(this)};
mz.prototype.start=function(){var a=this,b=!1;this.l.info(function(){b=!0;return"Starting next media remoting session."});b&&rz(this.h,function(b){return a.l.info(b)});sz(this.h);Ty(this.j,2,function(b){return(0,a.D)().then(function(c){a.s=c;Oy(a.B,"RPC",function(b){if(b.rpc){var c=a.h;b=b.rpc;c.s&&(++c.m,c.f+=b.length,c.s(b))}});Xy(b,3)}).catch(function(c){return pz(a).then(function(){Xy(b);throw c;})})}).then(function(){a.l.info("Remoting started successfully.")}).catch(function(b){a.l.error("Failed to start remoting",
b);a.b.onError()})};mz.prototype.start=mz.prototype.start;
mz.prototype.rq=function(a,b){var c=this;return Ty(this.j,3,function(d){return c.L.start(a?new az:null,b?new az:null,c).then(function(a){tz(c.h,function(a){return c.B.sendMessage(a)},function(a){c.b.onMessageFromSink(a)});Xy(d,4);return{audio_stream_id:a.Jn||-1,video_stream_id:a.zq||-1}}).catch(function(a){return pz(c).then(function(){Xy(d);throw a;})})}).catch(function(a){c.l.error("Failed to start remoting streams",a);nz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
mz.prototype.startDataStreams=mz.prototype.rq;mz.prototype.stop=function(a){var b=this;Uy(this.j,function(c){b.b.onStopped(a);return pz(b).then(function(){b.l.info("Remoting stopped.");Xy(c,5);(0,b.s)().then(function(){return Ty(b.j,5,function(a){if(b.b&&b.f)b.b.onSinkAvailable(b.C);Xy(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.s=null})}).catch(function(a){b.l.error("Failed to stop remoting: ",a);nz(b)})};mz.prototype.stop=mz.prototype.stop;
mz.prototype.co=function(){null===this.u&&(this.u=He(this.m.xb.bg).then(function(a){return a.f||!1}));return this.u.then(function(a){return{rate:(a?1E7:5E6)/8}})};mz.prototype.estimateTransmissionCapacity=mz.prototype.co;
var pz=function(a){return a.L.stop().then(function(){Py(a.B,"RPC");uz(a.h);vz(a.h)})},oz=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.l.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.l.error("Pref value not a boolean: "+JSON.stringify(c)):(a.f=!!c.value,a.l.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)||chrome.settingsPrivate.onPrefsChanged.addListener(a.o);b()})})};
mz.prototype.F=function(a){if(this.b){a=la(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.l.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.f==a)break;this.f=a;this.l.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.C);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var kz=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.qq||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,k=d.video_capabilities,m=b.le||"";(a.b||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.l.info("Unknown mediaCap name: "+a)}});b.le&&"Chromecast Ultra"==b.le&&k.push(f.SUPPORT_4K);return d},lz=function(){this.s=this.j=this.b=null;this.u=this.f=this.m=this.h=this.o=0;this.g=null},sz=function(a){a.b=[];wz(a,performance.now())},tz=function(a,b,c){a.j=b;a.s=
c;a.b?(b=a.b,a.b=null,b.forEach(function(b){return qz(a,b.data).then(b.bq,b.ol)})):wz(a,performance.now())},uz=function(a){if(a.b){var b=Error("Stop before delivering pending message");a.b.forEach(function(a){return a.ol(b)});a.b=null}a.j=null;a.s=null},qz=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.o;a.h+=b.length;return a.j({type:"RPC",rpc:c})}return a.b?new Promise(function(c,e){a.b.push({data:b,bq:c,ol:e})}):Promise.reject(Error("RPC pipe not started"))},rz=function(a,
b){vz(a);a.g=setInterval(function(){if(a.b)var c=a.b.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.u)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec) and ")+("received "+a.m+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";wz(a,c);c=d}b(c)},3E4)},vz=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},wz=function(a,b){a.o=0;a.h=0;a.m=0;a.f=0;a.u=b};var xz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},yz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var zz=function(a,b,c,d,e){this.h=new $y(a,b,c,d,void 0===e?null:e);this.l=qb("mr.mirror.cast.MediaStreamer");this.j=new Ry;this.g=this.f=this.b=this.s=null};zz.prototype.start=function(a,b){var c=this;return Ty(this.j,1,function(d){c.s=a;c.b=xz(a);c.b&&"ended"==c.b.readyState&&(c.b=null);c.f=yz(a);c.f&&"ended"==c.f.readyState&&(c.f=null);if(!c.b&&!c.f)return Xy(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.h.start(c.b,c.f,c.g).then(function(){return Xy(d,2)})})};
zz.prototype.stop=function(){var a=this;return Vy(this.j,function(b){return a.h.stop().then(function(){a.b=null;a.f=null;a.s=null;a.g=null;Xy(b,1)})})};var Az=function(a){return Ty(a.j,2,function(b){a.l.info("Suspending media streaming...");return a.h.stop().then(function(){a.l.info("Suspended media streaming.");Xy(b,3)})})};
zz.prototype.resume=function(){var a=this;return Ty(this.j,3,function(b){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.l.info("Resuming media streaming...");return a.h.start(a.b,a.f,a.g).then(function(){a.l.info("Resumed media streaming.");Xy(b,2)})})};var Bz=function(a,b,c){this.j=a;this.g=b;this.h=c;this.l=qb("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};Bz.prototype.start=function(){var a=this;null==this.b&&(xb(this.l,"Starting Wifi Status Monitoring."),this.f=[],Oy(this.h,"STATUS_RESPONSE",function(b){return Cz(a,b)}),this.b=setInterval(function(){return Dz(a)},12E4),Dz(this))};Bz.prototype.stop=function(){null!=this.b&&(xb(this.l,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,Py(this.h,"STATUS_RESPONSE"))};
var Cz=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.b&&(c.wifiSnr=b.status.b);null!=b.status.f&&(c.wifiSpeed=b.status.f[3]);0==Object.keys(c).length?v(a.l,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(c),a.l.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else v(a.l,function(){return"Ignoring response without status: "+JSON.stringify(b)})},Dz=function(a){a.h.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:tl(a.g),get_status:["wifiSnr","wifiSpeed"]})};var Ez=function(a,b,c,d){this.C=b.bg;this.m={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Sg(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.le};this.D=c;this.B=d;this.g=this.f=this.o=this.s=this.j=this.u=this.h=null;this.b=[]};Ez.prototype.yf=function(a){null!=this.f&&clearInterval(this.f);this.h=a;this.u=Date.now();this.f=setInterval(this.A.bind(this,a),9E5)};
Ez.prototype.gg=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.h){var a=this.A(this.h);this.h=null;return a}return Promise.resolve()};Ez.prototype.de=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.s=a():"string"===typeof a&&(this.s=a),b&&"string"===typeof b.stack&&(this.o=b.stack))};
var Gz=function(a,b){return(null==a.h?Promise.resolve():a.A(a.h)).then(function(){var c=b.map(function(b){b=Fz(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.cf}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),cf:new Blob(d,{type:"application/json"})}});a.b=[];return c})};
Ez.prototype.A=function(a){var b=this;if(null!=this.g)return this.g;var c=He(this.C).then(function(c){c={receiverVersion:c.b,receiverConnected:c.g,receiverOnEthernet:c.f,receiverHasUpdatePending:c.h,receiverUptimeSeconds:c.j};Object.assign(c,b.m);var d=Date.now();Object.assign(c,{startTime:b.u,endTime:d,activity:bz(a),receiverWifiStatus:Array.from(b.B.f)});b.u=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.s,streamingErrorCause:b.o}),b.j=null,b.s=null,b.o=null);return c});
return(this.g=Promise.all([c.then(function(b){return hz(a,b)}),c,iz(a)]).then(function(a){var c=la(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.b.push({events:a,cf:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.b=Fz(b,b.D);b.g=null}))||Promise.resolve()};
var Fz=function(a,b){b-=2;for(var c=[],d=a.b.length-1;0<=d;--d){b-=a.b[d].cf.size+1;if(0>b)break;c.push({events:null,cf:a.b[d].cf});if(null!=a.b[d].events){var e=a.b[d].events.size;b>=e&&(c[c.length-1].events=a.b[d].events,b-=e)}}return c.reverse()};var Hz=qb("mr.NetworkUtils"),Iz=function(a,b){return Vf?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(v(Hz,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Hz.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Jz=function(a,b,c,d){d=void 0===d?null:d;Pg.call(this,b);var e=b.xb;this.A=e.sessionId;this.C=e.bg;this.D=a;this.F=d;this.l=qb("mr.mirror.cast.Session");this.o=new Ry;this.m=new sl("mirror.cast.SeqNumGenerator");this.s=new Ny(b.id);this.j=new zz(e,this.D,this.m,this.s,this.F);this.g=null;this.b=new Ez(a,e,c,new Bz(this.A,this.m,this.s));this.f=!1;this.B=null};l(Jz,Pg);g=Jz.prototype;
g.start=function(a){var b=this;return Ty(this.o,1,function(c){var d=new Cb("MediaRouter.CastStreaming.Session.Launch");return Kz(b).then(function(c){b.f=c;return b.j.start(a,b)}).then(function(){if(b.j.h.B){var a=b.b;a.m.tdlsIsOn=b.f;a.B.start();Lz(b)}else b.b.m.tdlsIsOn=b.f;d.b();b.B=new Ib("MediaRouter.CastStreaming.Session.Length");Xy(c,2);return b})})};
g.stop=function(){var a=this;return Vy(this.o,function(b){a.B&&(a.B.b(),a.B=null);a.b.B.stop();return a.j.stop().then(function(){return a.g?nz(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?Mz(a):Promise.resolve()}).then(function(){a.f=!1;Xy(b,4)})})};g.ml=function(){var a={sessionId:this.A,seqNum:tl(this.m),type:"PRESENTATION",icons:[],title:Ng(this.Xb)};this.l.info("Sending session metadata update to receiver: "+this.A);this.s.sendMessage(a)};g.yf=function(a){this.b.yf(a)};g.gg=function(){return this.b.gg()};
g.de=function(a,b){this.b.de(a,b);this.l.error(a,b);this.stop()};
var Nz=function(a,b){return Gz(a.b,b)},Kz=function(a){return a.D.useTdls?Iz(a.C,!0).then(function(b){if("Connected"==b)return a.l.info("Successfully enabled TDLS."),!0;v(a.l,"Did not enable TDLS: result="+b);return!1}).catch(function(b){v(a.l,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Mz=function(a){return Iz(a.C,!1).catch(function(b){return a.l.error("Error while turning TDLS back off",b)})},Lz=function(a){Oz(a).then(function(b){(b.b||[]).includes("video")?Pz(a,b):v(a.l,
function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){v(a.l,"None/Invalid capabilites response. Media Remoting disabled.",b)})},Oz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.A,seqNum:tl(a.m)};a.l.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Qy(a.s,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.l.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;xb(a.l,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Pz=function(a,b){Ty(a.o,2,function(c){var d=a.h.xb.le||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return v(a.l,"HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
Xy(c),Promise.resolve();a.g=new mz(a.h,b,a.D,a.m,a.s,a.F);return a.g.fb(a.la.bind(a),a).catch(function(b){a.l.error("Media Remoting start failed: "+b.message,b)}).then(function(){return Xy(c)})})};Jz.prototype.la=function(){var a=this;return Ty(this.o,2,function(b){return new Promise(function(c,d){Az(a.j).then(function(){Xy(b,3);a.L=!0;Kg(a);c(a.M.bind(a))}).catch(function(b){a.de("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Jz.prototype.M=function(){var a=this;return Ty(this.o,3,function(b){return new Promise(function(c,d){a.j.resume().then(function(){Xy(b,2);a.L=!1;Kg(a);c()}).catch(function(b){a.de("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Qz=function(){Dg.call(this,"cast_streaming")};l(Qz,Dg);g=Qz.prototype;g.getName=function(){return"cast_streaming"};g.zg=function(a,b){return new Jz(a,b,20969472,null)};g.jh=function(){ny(0)};g.gh=function(){ny(1)};g.yi=function(){ny(2)};g.hh=function(){Nb("MediaRouter.CastStreaming.Session.End")};g.ih=function(a){Ob("MediaRouter.CastStreaming.Start.Failure",a,Rf)};g.Wf=function(){Nb("MediaRouter.CastStreaming.Stream.End")};
g.vh=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&uy(),e=[9351424];d&&e.push(20969472);return Nz(a,e).then(function(a){var e=a[a.length-1];a=uj(a[0].events).catch(function(a){b.J.error("Failed to persist events Blob.",a)});d&&0<e.events.size?qy(e.events,void 0,b.Po.bind(b)):c&&py("stats.json",e.cf,void 0,void 0);return a})})};g.Po=function(a){a&&(ty().b=Date.now())};
g.gi=function(a){this.J.info("Received message to upload logs for "+a);return this.b?Nz(this.b,[20969472]).then(function(b){b=la(b).next().value;return 0==b.events.size?"":qy(b.events,a)}):Promise.resolve(Rz(this,a))};
var Rz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return uj(new Blob),a.J.info("Uploading saved logs for feedback."),qy(c,b)},Sz=new Qz;tg("mr.mirror.cast.Service",Sz);
